#!/usr/bin/bash
curl http://www.nepalstock.com/todaysprice > /tmp/raw.html
grep -A 9 "td>[1-9]<" /tmp/raw.html > /tmp/stonk.html 
grep -A 9 "td>[1-9][0-9]<" /tmp/raw.html >> /tmp/stonk.html
sed -i '/--/d' /tmp/stonk.html 
python3 scripts/parse.py | sed -r '/^\s*$/d' > /tmp/less
less /tmp/less
rm /tmp/less /tmp/raw.html /tmp/stonk.html
